### ISSUE TITLE
Windows library install missing 64 bit setup

### ISSUE THREAD

**Issue by benpreisler** [dsuch/pymqi#217]
the setup.py for Windows assumes that 
- if you have 64 bit python installed you have a 32 bit version of MQ installed on a 64 bit Windows machine
- if you have 32 bit python installed you have a 64 bit version of MQ installed on a 64 bit Windows machine (or 32 on 32 but not unlikely)

- 64 bit python with 64 bit MQ installed on a 64 bit machine isn't supported by the setup install

https://github.com/dsuch/pymqi/blob/master/setup.py#L31

**Comment by dsuch** [comment]
Hi @benpreisler,

you may be correct, I do not use Windows and I am not sure who else around here does, so this can be likely the case.

Can you suggest what changes to make? Have you perhaps worked it out already?

Regards.

**Comment by dsuch** [comment]
Also, one question, does this block not cover your use case?

```python
    if bits == 64:
        library_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64',
                        r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include',
                        r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
```

**Comment by benpreisler** [comment]
c:\Program Files (x86) is where 32 bit programs are installed on a Win 64 machine (64 bit programs are installed under c:\Program Files)

I guess one question I have is Lib64 vs Lib - should the choice here correspond to the python version or the system version?

**Comment by dsuch** [comment]
Not being a Windows user, I honestly do not know and cannot make a call here - let us wait for others to join the discussion.

**Comment by benpreisler** [comment]
ok cool - I'll add some more info:

you can use `calcsize('P')` to find out the if the python interpreter is 32 vs 64 but you can have 32bit python installed on a 64 bit machine or vice versa.  (32 bit is actually the default for Windows if you download from pythons website)

So that is fine if we need to know the python interpreter install version but if what we really want to know is the system architecture then we can use: https://docs.python.org/3/library/platform.html#platform.architecture
```
from platform import architecture
print(architecture()[0])
```
should give you 64bit or 32bit

so if Lib is correlated to the system then for a 64 bit system with a 64 bit MQ client installed it would need to look: 

c:\Program Files\IBM\WebSphere MQ\tools\Lib64
and for 32 bit system with 32 bit MQ:
c:\Program Files\IBM\WebSphere MQ\tools\Lib
and for 64 bit system with 32 bit MQ:
c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64

**Comment by JoshMcMQ** [comment]
You should point to lib (32bit) or lib64 (64bit) basted on the binary not the OS.  MQ installs everything in one main folder with those two sub folders.

**Comment by SeyfSV** [comment]
@benpreisler , do you have issues with install? I added installation tests for windows x86 - it passed [successfully](https://github.com/dsuch/pymqi/runs/829827340?check_suite_focus=true)

pymqi installation does not require user for selecting right paths.
There are some exceptions, like custom MQ installation path, multiple MQ installations and others...
pymqi tries to use defaultl paths, if it can't - tries to find dspmqver (PATH variable used) and use path to it.
Also you can set MQ_FILE_PATH to help pymqi to search MQ.

**Comment by benpreisler** [comment]
> You should point to lib (32bit) or lib64 (64bit) basted on the binary not the OS. MQ installs everything in one main folder with those two sub folders.

**Comment by benpreisler** [comment]
Yes windows machines there are issues with the pymqi install because it appears that setup is looking in the wrong folder for the MQ libs

**Comment by benpreisler** [comment]
Ok so it sounds like it needs to pick based on the python interpreter binary.  If the MQ_FILE_PATH override path works I can set it up that way (I was unsure about that since both the bad location and the MQ_FILE_PATH location are added but it sounds like that is fine).

The normal pathing still does have some issues though even if MQ_FILE_PATH can override them:
```
    if bits == 64:
        library_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64',
                        r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include',
                        r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
    else:
        library_dirs = [r'c:\Program Files\IBM\WebSphere MQ\Tools\Lib',
                        r'{}\tools\Lib'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files\IBM\WebSphere MQ\tools\c\include',
                        r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
```

The problem is that if the user has a 64bit python binary then it will only (by default) look for a 32bit MQ client (under Program Files (x86))
If the user has a 32bit python binary it will look for a 64bit MQ library (this is the most common setup) or for a 32bit MQ lib if installed on a 32bit Windows machine (very uncommon I'd think)

If it's ok to have multiple dir paths in the ext_modules then I would maybe suggest:
```
    if bits == 64:
        library_dirs = [r'c:\Program Files\IBM\WebSphere MQ\tools\Lib64',
                        r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64',
                        r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files\IBM\WebSphere MQ\tools\c\include',
                        r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include',
                        r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
``` 
but if the user has installed both 32 and 64 bit version of MQ then I don't know if that would cause issues or not (probably it would be fine as long as the correct dir path is there)

**Comment by JoshMcMQ** [comment]
The install location is arbitrary and has always be customizable on Windiws.

Over time there default has changed:

* MQ 7.5 and lower MQ client and server were were 32bit only (but supported 64bit applications) and defaulted to `C:\Program Files (x86)\WebSphere MQ`
* MQ 8.0 client is available in 32bit or 64bit, 32bit default remains the same as 7.5 and lower, 64bit defaults to `C:\Program Files\IBM\WebSphere MQ`.
*  MQ 8.0 and later server is available in 64bit only (but supports 32bit applications),  the location defaults to `C:\Program Files\IBM\WebSphere MQ`.
* MQ 9.0 or later client is available in 64bit only (but supports 32bit applications),  the location defaults to `C:\Program Files\IBM\WebSphere MQ`.

In all cases it is just a default for new installs on a server without an existing install to upgrade.   If upgrading an existing install the location will stay the same unless a custom location is specified.

There is more info [here](https://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.pro.doc/q119400_.htm).

Note that the data directory also changed (prior to v8.0 the data and binary directory were one and the same) to default to `C:\ProgramData\IBM\MQ` in this case only for a brand new installs, any upgraded even if the prior version was removed will be the original data directory.   This could mean that MQ binaries are in one location and data in another.  If defaults were used in 7.5 or earlier and then that install was removed and 8.0 or later installed with defaults then binaries would be in `Program Files` and data in `Program Files (x86)`.

Further you can install multiple versions on windows at the same time in different directories.   The first install will by default be set to the Primary install.   Primary install means that the location will be included in the windows system `Path` and some other variables.  Any install can be primary,  but there is always one primary on windows. 

The location of the primary install is always set in the `MQ_FILE_PATH` system environment variable (unless someone manually removes this).

Based on this,  I think this can be simplified to just the following:

```
    if bits == 64:
        library_dirs = [r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
    else:
        library_dirs = [r'{}\tools\Lib'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
```

As I mentioned above you should point to `lib` (32bit) or `lib64` (64bit) under `MQ_FILE_PATH\tools` based on the binary not the OS.

**Comment by SeyfSV** [comment]
ok, please, describe your environment:
* windows version and architecture
* MQ client version, location
* MQ installation way: default setup?, custom setup?, redistributable client (just a zip file)?
* `dspmqver` output (yes, it's cover other questions)
* PATH and MQ_* environment variables
* python version and architecture
* pymqi version: release or some of commits?

**Comment by benpreisler** [comment]
> ok, please, describe your environment:
> 
> * windows version and architecture
Windows 10 64bit
> * MQ client version, location
9.1.0.5-IBM-MQC-Win64
https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+MQ&release=9.1.0.5&platform=Windows+64-bit,+x86&function=fixId&fixids=9.1.0.5-IBM-MQC-*,9.1.0.5-IBM-MQC-Win64&useReleaseAsTarget=true&includeSupersedes=0
> * MQ installation way: default setup?, custom setup?, redistributable client (just a zip file)?
default setup
> * `dspmqver` output (yes, it's cover other questions)
not sure what you mean here
> * PATH and MQ_* environment variables
C:\Program Files\IBM\MQ\bin64;
C:\Program Files\IBM\MQ\bin;
C:\Program Files\IBM\MQ\tools\c\samples\bin64;
C:\Program Files\IBM\MQ\tools\c\samples\bin;
> * python version and architecture
python 3.8.0 32bit or 64bit (both used)
> * pymqi version: release or some of commits?
1.10.1

JoshMcMQ's suggestion makes sense to me - always set the MQ_FILE_PATH as a requirement for Win installs

**Comment by JoshMcMQ** [comment]
The two things missed:

1. `"C:\Program Files\IBM\MQ\bin64\dsomqver`

2. `set | findstr "MQ_"`

Can you also explain what is not working?   Does pymqi fail when you attempt to connect to the queue manager?  If it fails can you provide the full error and stack?

**Comment by SeyfSV** [comment]
1. MQ_FILE_PATH processing for Windows was added in one of the last commits and it is in release 1.12.
Please, try it
2. Provide installation output with error

**Comment by benpreisler** [comment]
> The two things missed, run these commands:
> 
> 1. `"C:\Program Files\IBM\MQ\bin64\dsomqver"`
> 2. `set | findstr "MQ_"`
> 
> Can you also explain what is not working? Does pymqi fail when you attempt to connect to the queue manager? If it fails can you provide the full error and stack?

![dspmqver and MQ_](https://user-images.githubusercontent.com/17465718/86618807-24f4db80-bf7f-11ea-8e4e-e229934ba92d.png)

It's just what we were discussing - it looks in the wrong place by default.  We'll try the MQ_FILE_PATH which I assume will work.  Previously some team members we're getting around it by installing MQ in both places which isn't good

**Comment by benpreisler** [comment]
> 1. MQ_FILE_PATH processing for Windows was added in one of the last commits and it is in release 1.12.
>    Please, try it
> 2. Provide installation output with error

1. we will try MQ_FILE_PATH - I assume it will work

2: 

Collecting pymqi==1.10.1
  Using cached pymqi-1.10.1.tar.gz (70 kB)
Using legacy setup.py install for pymqi, since package 'wheel' is not installed.
Installing collected packages: pymqi
    Running setup.py install for pymqi ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\PycharmProjects\project_1\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-hq2m3uir\\pymqi\\setup.py'"'"'; __file__='"'"'C:\\Users\
\****\\AppData\\Local\\Temp\\pip-install-hq2m3uir\\pymqi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\****\AppData\Local\Temp\pip-record-94v0tq9r\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\PycharmProjects\project_1\venv\include\site\python3.8\pymqi'
         cwd: C:\Users\****\AppData\Local\Temp\pip-install-hq2m3uir\pymqi\
    Complete output (22 lines):
    Building PyMQI client mode 64bits
    Using library_dirs:`['c:\\Program Files (x86)\\IBM\\WebSphere MQ\\tools\\Lib64']`, include:`['c:\\Program Files (x86)\\IBM\\WebSphere MQ\\tools\\c\\include']`, libraries:`['mqic']`
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pymqi
    copying pymqi\__init__.py -> build\lib.win-amd64-3.8\pymqi
    copying pymqi\CMQC.py -> build\lib.win-amd64-3.8\pymqi
    copying pymqi\CMQCFC.py -> build\lib.win-amd64-3.8\pymqi
    copying pymqi\CMQXC.py -> build\lib.win-amd64-3.8\pymqi
    copying pymqi\CMQZC.py -> build\lib.win-amd64-3.8\pymqi
    running build_ext
    building 'pymqi.pymqe' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\pymqi
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYQMI_BINDINGS_MODE_BUILD=0 "-Ic:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include" -IC:\PycharmProjects\project_1\venv\include -IC:\Users\****\AppData\Local\Programs\Python\Python38\include -IC:\Users\****\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.2861
0\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Fil
es (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" "-IC
:\Program Files\IBM\MQ\tools\c\include" "-IC:\Program Files\IBM\MQ\tools\cplus\include" /Tcpymqi/pymqe.c /Fobuild\temp.win-amd64-3.8\Release\pymqi/pymqe.obj
    pymqe.c
    pymqi/pymqe.c(78): fatal error C1083: Cannot open include file: 'cmqc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\PycharmProjects\project_1\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-hq2m3uir\\pymqi\\setup.
py'"'"'; __file__='"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-hq2m3uir\\pymqi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))
' install --record 'C:\Users\****\AppData\Local\Temp\pip-record-94v0tq9r\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\PycharmProjects\project_1\venv\include\site\python3.8\pymqi' Check the logs
 for full command output.

**Comment by JoshMcMQ** [comment]
As you output does show the install is primary and `MQ_FILE_PATH` is set to the install location, why does this fail?  The 2nd choice should resolve? 

```
    if bits == 64:
        library_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64',
                        r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include',
                        r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
    else:
```

**Comment by benpreisler** [comment]
> As you output does show the install is primary and `MQ_FILE_PATH` is set to the install location, why does this fail? The 2nd choice should resolve?
> 
> ```
>     if bits == 64:
>         library_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\Lib64',
>                         r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
>         include_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include',
>                         r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
>     else:
> ```

Oh I guess I didn't state that clearly - with updated code and the the MQ_FILE_PATH override it works fine - I was meaning that the defaults were a little weird then because they include both directories.  your changes look good to me.  Thats all - thanks!

**Comment by JoshMcMQ** [comment]
The error has to do with the header file on a specific lib directory:

```
pymqi/pymqe.c(78): fatal error C1083: Cannot open include file: 'cmqc.h': No such file or directory
```

I see the compile command includes this:
```
"-IC
:\Program Files\IBM\MQ\tools\c\include"
```

Can you confirm this path has `cmqc.h`?

**Comment by benpreisler** [comment]
yes - cmqc.h is in that path

**Comment by JoshMcMQ** [comment]
To clear it up for me does it work with unmodified 1.12?

**Comment by benpreisler** [comment]
only if you set MQ_FILE_PATH

**Comment by JoshMcMQ** [comment]
You confirmed this was set.  You didn't need to manually set it did you? 

I mentioned previously: Any install can be primary, but there is always one primary on windows.

The location of the primary install is always set in the MQ_FILE_PATH system environment variable (unless someone manually removes this).

If you did not have this variable it would strange.

**Comment by benpreisler** [comment]
yeah we had to manually set the MQ_FILE_PATH - what should have set that?  The IBM MQ lib?

**Comment by JoshMcMQ** [comment]
The MQ client install will set that as a global variable if you are using a full client (setup.exe) and not a Redist client (simple zip file).

**Comment by benpreisler** [comment]
ok with a clean install I can confirm MQ_FILE_PATH is being added by the MQ setup

**Comment by dsuch** [comment]
You are welcome @benpreisler.

**Comment by atulk0** [comment]
@JoshMcMQ, the default install path of MQ version 7.5 and 8.0 is correct. However, for some reason IBM has dropped the Websphere name from version 9 onward. The default install location version 9.0 onward is "C:\Program Files\IBM\MQ". Please refer
[https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.mig.doc/q119400_.htm](here) for detail.

**Comment by JoshMcMQ** [comment]
@atulk0 thank you for the link.

I think then here the logic should be `MQ_FILE_PATH` first, new 9.0 and later default second,  finally 8.0 and prior default.

**Comment by atulk0** [comment]
@JoshMcMQ yes, I think that would make more sense.

**Comment by atulk0** [comment]
@JoshMcMQ I see @benpreisler also highlighted that the 32 bit directory is "Program Files (x86)" and 64 bit path is "Program Files", I think this needs to be changed as well in the setup.

**Comment by JoshMcMQ** [comment]
32bit MQ Server doesn't exist at 8.0 and later, 64bit MQ Client doesn't exist at 9.0 and later.  So 32bit only makes sense at those earlier levels.  Since 8.0 is out of support we could probably just ignore those.   In any case the 1st installed client on windows is always set as primary and sets `MQ_FILE_PATH` by default unless you run a command to make it not the default.  If anyone is running 32bit client or server at an older version the `MQ_FILE_PATH` will be available.

**Comment by atulk0** [comment]
@JoshMcMQ, I agree, it would make more sense to make the 64 bit part compatible with MQ version 9.0 or above and still leave the 32 bit part to support older versions. It could be something like this:
```

if bits == 64:
        library_dirs = [r'c:\Program Files\IBM\MQ\tools\Lib64',
                        r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files\IBM\MQ\tools\Lib64',
                        r'{}\tools\Lib64'.format(os.environ['MQ_FILE_PATH'])]
    else:
        library_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\Tools\Lib',
                        r'{}\tools\Lib'.format(os.environ['MQ_FILE_PATH'])]
        include_dirs = [r'c:\Program Files (x86)\IBM\WebSphere MQ\tools\c\include',
                        r'{}\tools\c\include'.format(os.environ['MQ_FILE_PATH'])]
```

**Comment by JoshMcMQ** [comment]
The `lib` and `lib64` are both available in either a 32bit or 64bit install of MQ. What is the source of `bits`?  If this is related to the bits of python then this logic does make sense.   Also as described in my prior comment those paths are only defaults for fresh installs.  I think it is best to rely on `MQ_FILE_PATH` which should be set by any install since MQ7.1 which itself has been out of support over three years (2017-04-30).
